@PORT = 3000
@HOST = http://localhost:{{PORT}}


###     
POST {{HOST}}/api/autores
Content-Type: application/json

{
    "nombre": "Luis Roberto Lopez",
    "email": "luis@gmail.com",
    "imagen": ""
}

###
GET {{HOST}}/api/autores/1
Content-Type: application/json

###     
POST {{HOST}}/api/posts/
Content-Type: application/json

{
    "titulo": "Final NBA",
    "descripcion": "LUNES DE FINALES DE NBA",
    "fecha_creacion": "2024/05/31",
    "categoria": "Deportes",
    "autores_id": "1"
}

###
GET {{HOST}}/api/posts/1
Content-Type: application/json

