@PORT = 3000
@HOST = http://localhost:{{PORT}}


###     
POST {{HOST}}/api/autores
Content-Type: application/json

{
    "nombre": "Pepe Lopez",
    "email": "Pepe@gmail.com",
    "imagen": ""
}

###
GET {{HOST}}/api/autores/1
Content-Type: application/json

###     
POST {{HOST}}/api/posts/
Content-Type: application/json

{
    "titulo": "Bandas de Rock",
    "descripcion": "Las 10 mejores bandas de rock de MX",
    "fecha_creacion": "2024/05/31",
    "categoria": "Deportes",
    "autores_id": "2"
}

###
GET {{HOST}}/api/posts/1
Content-Type: application/json

###
GET {{HOST}}/api/autores/posts/2
Content-Type: application/json

